### PR TITLE
Implement Codey models

### LINKED ISSUE #175: Implement VertexAI models
Currently, we are only using chat-bison and text-bison. Implement any other vertexAI models:
- text-bison
- chat-bison
- code-bison
- codechat-bison
- code-gecko

https://cloud.google.com/vertex-ai/generative-ai/docs/code/code-models-overview

### PR DESCRIPTION
**Pull request by BallenAlain**
Resolves #175 

- Implement Codey API models
- Fix chat-bison issue -> chat-bison uses ChatModel not TextGenerationModel
- integration tests: updated google auth workload identity provider and service account

@dinuja9 add context to the start_chat() functions

### CODE REVIEW

**Review by dinuja9 — COMMENTED** [review]
Is this error something to do with the google project ID, or application credential key?
image

**Comment by BallenAlain** [comment]
> Is this error something to do with the google project ID, or application credential key? image

Yes, you probably have outdated credentials. I sent you the updated ones

**Comment by dinuja9** [comment]
> > Is this error something to do with the google project ID, or application credential key? image
> 
> Yes, you probably have outdated credentials. I sent you the updated ones

yup, it works now, thanks!

**Review by dinuja9 — APPROVED** [review]
Everything looks good and works fine

**Pull request merged**
